project_id = "ywixtqxtftcwdvxduwwx"

[functions.backup-manager]
verify_jwt = true

[functions.init-user-session]
verify_jwt = true

[functions.manage-roles]
verify_jwt = true

[functions.monitoring-integrations]
verify_jwt = false

[functions.notification-dispatcher]
verify_jwt = false

[functions.generate-document]
verify_jwt = false

[functions.security-patch-scheduler]
verify_jwt = true

[functions.vulnerability-scanner]
verify_jwt = true

[functions.cloud-orchestration]
verify_jwt = false