project_id = "ywixtqxtftcwdvxduwwx"

[functions.init-user-session]
verify_jwt = true

[functions.manage-roles]
verify_jwt = true

[functions.security-patch-scheduler]
verify_jwt = true

[functions.vulnerability-scanner]
verify_jwt = true