// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ywixtqxtftcwdvxduwwx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl3aXh0cXh0ZnRjd2R2eGR1d3d4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIxNjQzMDcsImV4cCI6MjA2Nzc0MDMwN30.gwNEVQlmFc720YZEWzynHkYIWrX-b1RSRGsRhCVA-NQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});